name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: "16"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Cache .yarn/cache
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: v2-${{ runner.os }}-yarn_cache
          restore-keys: |
            v2-${{ runner.os }}-          
      
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules/**
            packages/*/node_modules/**
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v2-${{ runner.os }}-node_modules-
            v2-${{ runner.os }}-          

      - run: yarn install --immutable

  lib-site-build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules/**
            packages/*/node_modules/**
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      
      - run: yarn lib:build && yarn lib:build-docs && yarn site:build
  
  lib-test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules/**
            packages/*/node_modules/**
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn lib:test -i --coverage && yarn codecov -p ./packages/lib
